# Generated by Django 3.0.8 on 2020-08-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='Biography to come', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.URLField(default='https://image.flaticon.com/icons/svg/104/104784.svg'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
