# Generated by Django 3.0.8 on 2020-08-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
