# Generated by Django 3.0.8 on 2020-08-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200801_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
