# Generated by Django 3.0.8 on 2020-08-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200801_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1474221379956-afaf88e3d760?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1296&q=80'),
            preserve_default=False,
        ),
    ]
